[UnitTest] Attempt to fix link to DataLayoutTest_UEFI_Test
This is failing in a few buildbots to link due to missing references to
undefined reference to llvm::Triple::Triple from DataLayoutTest_UEFI_Test.
Attempt to fix them by adding the TargetParser lib for IR unit tests.